### ISSUE TITLE
Windows formatting

### ISSUE THREAD

**Issue by ArasDawn** [DesWurstes/vanitygen#2]
On Windows, both on Command Prompt and PowerShell, it shows:

```
vanitygen-cash.exe qras
Difficulty: [36m4096[0m
[0mPattern: [33mqras[0m
Address: [32mbitcoincash:qrasnlrusum9hln4rj8q48j7nvtggr2atvmac9r24n[0m
Privkey: [34m5KSBJQFWPuNxC3o4bAR8cN97WS6Qy59BdLeBEP1QMqUZdtHHp73[0m
```

As you see, the color characters don't work.

**Comment by DesWurstes** [comment]
Thank you for your bug report, I'll make colored output optional in the next release, which'll solve both of the issues.

**Comment by DesWurstes** [comment]
[Windows.zip](https://github.com/cashaddress/vanitygen-cash/files/1778697/Windows.zip)
Here's an early release that solves both issues.
