### ISSUE TITLE
memory leak with regex

### ISSUE THREAD

**Issue by markblundeberg** [DesWurstes/vanitygen#4]
When doing regex keys, each key processed seems to eat up approximately 60 bytes of memory (1 GB for 17 million keys). As a result, after about a minute of running the program has eaten up all my memory and starts to swap.

(running on linux; ubuntu 17.10)

**Comment by DesWurstes** [comment]
Thank you for the feedback. I guess the problem is caused by that it uses PCRE from 2015. I hope switching to PCRE2 will solve the issues.
UPDATE: After reading the whole PCRE2 documentation, I decided to switch to Hyperscan. It might take a few days.

**Comment by DesWurstes** [comment]
Switched to Hyperscan one week ago. Now it's more efficient and significantly faster.
